[".tmux/plugins/tmux-resurrect"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tmux-resurrect"

[".config/sketchybar/plugins/icon_map.sh"]
type = "file"
url = "https://github.com/kvndrsslr/sketchybar-app-font/releases/latest/download/icon_map.sh"
executable = true
refreshPeriod = "168h"
