gui:
  theme:
    activeBorderColor:
      - "#f6c177"
      - "bold"
    inactiveBorderColor:
      - "#6e6a86"
    optionsTextColor:
      - "#6e6a86"
    selectedLineBgColor:
      - "#44415a"
    defaultFgColor:
      - "#e0def4"
